### PR TITLE
[Tree][NestedSet] Fix TreeRoot without rootIdentifierMethod when calling getNextSiblings

### LINKED ISSUE #2517: [Tree][NestedSet] getNextSiblings when "rootIdentifierMethod" is not set
# Description

When using `TreeRoot` attribute/annotation, the `getNextSiblings` method crashes when it tries to get node's `root` value on top node (with no parent).

It results with a `Error: Method name must be a string` error due to:
```php
$method = $config['rootIdentifierMethod'];
$qb->setParameter('root', $node->$method());
```

# How to reproduce

Category entity:
```php

    #[Gedmo\TreeRoot]
    #[ORM\ManyToOne(targetEntity: self::class)]
    #[ORM\JoinColumn(name: 'tree_root', referencedColumnName: 'id', onDelete: 'CASCADE')]
    private $root;
```

Test code:
```php
$food = new Category();
$food->setTitle('Food');

$this->em->persist($food);
$this->em->flush();

$categoryRepository->getNextSiblings($food);
```

### PR DESCRIPTION
**Pull request by Jean-Beru**
Fixes #2517

### CODE REVIEW

File: tests/Gedmo/Tree/Fixture/Issue2517/Category.php [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+    {
+        return $this->title;
+    }
+
+    public function getRoot(): ?self
+    {
+        return $this->root;
+    }
+
+    public function setParent(self $parent = null): void
```
Comment (phansys) [inline tests/Gedmo/Tree/Fixture/Issue2517/Category.php:134]:
```suggestion
    public function setParent(?self $parent): void
```

**Review by franmomu — APPROVED** [review]

**Review by phansys — APPROVED** [review]

**Comment by phansys** [comment]
Thank you @Jean-Beru!
