### PR TITLE
Add hacky fix for Doctrine Bundle 2.3

### LINKED ISSUE #2210: Gedmo Extension Tree not longer working with DoctrineBundle 2.3 Version
As seen in https://github.com/doctrine/DoctrineBundle/issues/1305 there where some breaking changes which will not be changed there. So we will need to adjust the gedmo extension to use the new `getDriver` which will be introduce in https://github.com/doctrine/DoctrineBundle/pull/1304. I did currently not yet get it to work but maybe @stof know more what we need to change here to get it again using gedmo over the doctrine bundle with https://github.com/stof/StofDoctrineExtensionsBundle. 

## Here the Original Issue

I updated in our project only `doctrine/doctrine-bundle` from `2.2.3` to `2.3.0`.

After the update I'm getting the following when the `cache:clear` is called:

> In TreeListener.php line 71:
>  Tree object class: Sulu\Bundle\MediaBundle\Entity\Collection must have tree metadata at this point

<details>
<summary>Stack Trace</summary>

```bash
Exception trace:
  at /private/tmp/sulu-develop.localhost/vendor/gedmo/doctrine-extensions/src/Tree/TreeListener.php:71
 Gedmo\Tree\TreeListener->getStrategy() at /private/tmp/sulu-develop.localhost/vendor/gedmo/doctrine-extensions/src/Tree/Entity/Repository/NestedTreeRepository.php:891
 Gedmo\Tree\Entity\Repository\NestedTreeRepository->validate() at /private/tmp/sulu-develop.localhost/vendor/gedmo/doctrine-extensions/src/Tree/Entity/Repository/AbstractTreeRepository.php:53
 Gedmo\Tree\Entity\Repository\AbstractTreeRepository->__construct() at /private/tmp/sulu-develop.localhost/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:79
 Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory->getOrCreateRepository() at /private/tmp/sulu-develop.localhost/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:65
 Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory->getRepository() at /private/tmp/sulu-develop.localhost/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:758
 Doctrine\ORM\EntityManager->getRepository() at /private/tmp/sulu-develop.localhost/var/cache/website/prod/ContainerVYSWbWN/EntityManager_9a5be93.php:153
 ContainerVYSWbWN\EntityManager_9a5be93->getRepository() at /private/tmp/sulu-develop.localhost/var/cache/website/prod/ContainerVYSWbWN/App_KernelProdContainer.php:2196
 ContainerVYSWbWN\App_KernelProdContainer->getSuluMedia_CollectionRepositoryService() at /private/tmp/sulu-develop.localhost/var/cache/website/prod/ContainerVYSWbWN/App_KernelProdContainer.php:2314
 ContainerVYSWbWN\App_KernelProdContainer->getSuluMedia_MediaManagerService() at /private/tmp/sulu-develop.localhost/var/cache/website/prod/ContainerVYSWbWN/App_KernelProdContainer.php:958
 ContainerVYSWbWN\App_KernelProdContainer->get_Container_Private_TwigService() at /private/tmp/sulu-develop.localhost/vendor/symfony/dependency-injection/Container.php:441
 Symfony\Component\DependencyInjection\Container->getService() at /private/tmp/sulu-develop.localhost/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:42
 Symfony\Component\DependencyInjection\Argument\ServiceLocator->get() at /private/tmp/sulu-develop.localhost/vendor/symfony/twig-bundle/CacheWarmer/TemplateCacheWarmer.php:46
 Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer->warmUp() at /private/tmp/sulu-develop.localhost/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:98
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /private/tmp/sulu-develop.localhost/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:243
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /private/tmp/sulu-develop.localhost/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:155
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /private/tmp/sulu-develop.localhost/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /private/tmp/sulu-develop.localhost/vendor/symfony/console/Application.php:989
 Symfony\Component\Console\Application->doRunCommand() at /private/tmp/sulu-develop.localhost/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /private/tmp/sulu-develop.localhost/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /private/tmp/sulu-develop.localhost/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /private/tmp/sulu-develop.localhost/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /private/tmp/sulu-develop.localhost/bin/console.php:51
 include() at /private/tmp/sulu-develop.localhost/bin/websiteconsole:7

```

</details>

I also tried the https://github.com/doctrine/DoctrineBundle/pull/1304 PR but seems like this does not fix it, still the same error.

Not sure yet which cause the issue, happy for every hint.

PS: After debugging it in more details with git bisect it has todo with the changes in https://github.com/doctrine/DoctrineBundle/pull/1284.

#### Reproduceable Repository

```bash
composer create-project sulu/skeleton
```

```bash
bin/websiteconsole cache:clear
```

### PR DESCRIPTION
**Pull request by AkenRoberts**
Attempting to resolve #2210 with a quick fix.

The larger problem involves how Doctrine Extensions manages class metadata, and it piggybacking on top of the ORM metadata classes and drivers. Ideally, this would be separated into Extensions' own metadata logic and storage system.

Unfortunately, that large fundamental infrastructure change is unlikely in the near future. So, just trying to do what we can to keep things running until that time may come.

### CODE REVIEW

File: src/Mapping/ExtensionMetadataFactory.php [hunk 1]
```diff
@@ -137,6 +138,12 @@ public static function getCacheId($className, $extensionNamespace)
      */
     protected function getDriver($omDriver)
     {
+        if ($omDriver instanceof DoctrineBundleMappingDriver) {
+            $omDriver = (new \ReflectionClass($omDriver))
+                ->getProperty('driver')
+                ->getValue($omDriver);
```
Comment (alexander-schranz) [inline src/Mapping/ExtensionMetadataFactory.php:144]: Getting the following error:

> In FileLoader.php line 173:
>
>  Cannot access non-public property Doctrine\Bundle\DoctrineBundle\Mapping\MappingDriver::$driver in /sulu-cms.localhost/vendor/sulu/sulu/src/Sulu/Bun
  dle/ContactBundle/Resources/config/routing_api.yml (which is being imported from "/Users/sulu-cms.localhost/config/routes/sulu_admin.yaml"). Make sure the
>  re is a loader supporting the "rest" type.
>
>
> In ExtensionMetadataFactory.php line 145:
>
>  Cannot access non-public property Doctrine\Bundle\DoctrineBundle\Mapping\MappingDriver::$driver

I think here is the `setAccessible` call missing:

```suggestion
            $propertyReflection = (new \ReflectionClass($omDriver))
                ->getProperty('driver');
            $propertyReflection->setAccessible(true);
            $omDriver = $propertyReflection->getValue($omDriver);
```

**Review by alexander-schranz — COMMENTED** [review]
I hope there will be a better solution in the future, as the reflection will only work for the current class and if somebody would decorate the `MappingDriver` service this would not work. With my suggested change it did work for me.

**Comment by AkenRoberts** [comment]
Thank you, I had a feeling it was missing something but since I'm not set up to replicate the issue I'm a bit blind.

You're 100% right, this is definitely not an ideal fix. But ideal would mean being stuck at DoctrineBundle 2.2.x for a _long_ time, probably. I want to unstick people more than I want a perfect library at this point.

**Comment by alexander-schranz** [comment]
@AkenRoberts sure, thank you for having a look at this 👍

**Review by alexander-schranz — APPROVED** [review]
The error is gone with this quickfix in @sulu.

**Comment by chapterjason** [comment]
My case works also with this fix. 👍🏼

**Review by chapterjason — APPROVED** [review]

**Comment by AkenRoberts** [comment]
Very grateful for your help, Alexander and Jason! 👏🏼

**Comment by alexander-schranz** [comment]
@AkenRoberts Thank you for the fast release 👍
