### PR TITLE
[Translatable] Fix mixing attributes and annotations

### LINKED ISSUE #2321: Translatable with attributes and annotations
In https://github.com/doctrine-extensions/DoctrineExtensions/pull/2253 I added support for attributes for Translatable extension, but I missed mixing attributes and annotations.

The problem I've found is that the driver used (`Annotation`, `Attribute`, etc) is based on the doctrine configuration:

https://github.com/doctrine-extensions/DoctrineExtensions/blob/46e102535be5eb978549520cc3645a1571cb4c03/src/Mapping/ExtensionMetadataFactory.php#L141-L196

So if someone has defined its mapping using attributes, it uses the `AttributeReader` and it won't be able to read our annotations.

We could maybe create another reader with both `AttributeReader` and `AnnotationReader` and try with attributes and then fallback to annotations.

I'll try to implement it, but not sure if I have time this week.

The solution for someone facing these issues is to use attributes for the Translatable extension in the meantime.

### PR DESCRIPTION
**Pull request by franmomu**
Fixes #2321

It adds a new `AttributeAnnotationReader` which tries to read attributes and if it fails, it reads annotations.

### CODE REVIEW

File: src/Mapping/Driver/AttributeAnnotationReader.php [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+        if (null !== $annotation) {
+            return $annotation;
+        }
+
+        return $this->annotationReader->getPropertyAnnotation($property, $annotationName);
+    }
+
+    public function getMethodAnnotations(ReflectionMethod $method)
+    {
+        throw new \LogicException('Not implemented');
```
Comment (phansys) [inline src/Mapping/Driver/AttributeAnnotationReader.php:86]:
```suggestion
        throw new \BadMethodCallException('Not implemented.');
```

File: src/Mapping/Driver/AttributeAnnotationReader.php [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+    }
+
+    public function getMethodAnnotation(ReflectionMethod $method, $annotationName)
+    {
+        throw new \LogicException('Not implemented');
```
Comment (phansys) [inline src/Mapping/Driver/AttributeAnnotationReader.php:91]:
```suggestion
        throw new \BadMethodCallException('Not implemented.');
```

**Review by phansys — APPROVED** [review]

**Comment by phansys** [comment]
Thank you @franmomu!
